spring:
  profiles:
    active: prod
  application:
    name: startmap
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${application-prod.yml:13}
            redirect_uri: ${kakao.redirect_uri}
            client-secret: ${kakao.password}
            client-name: startmap
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  batch.jdbc.initialize-schema: always

server:
  port: 8080

jwt:
  header: ${jwt.header}
  secret: ${jwt.secret}
  token-validity-in-seconds: ${jwt.token-validity-in-seconds}

